services:
  nodejs:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: vite:latest
    container_name: vite
    volumes:
      - .:/app
    ports:
      - '7777:7777'
