services:
  nodejs:
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: frontend-dev:latest
    container_name: frontend-dev
    volumes:
      - ../:/app
    ports:
      - '7777:7777'
